# ðŸŒŸ SkyXEvents - Random Chest Spawn Settings
prefix: "&c&lSky X &f&lChristmas >>"

world: "world"           # world where chests spawn
spawn_interval_seconds: 1200  # every 20 minutes (1200 sec)

min_x: -2000
max_x: 2000
min_z: -2000
max_z: 2000

# Chest pool configuration
# Each chest definition is stored in /chests/*.yml
chests_path: "chests"
auto_remove_seconds: 600  # 10 minutes